services:
  mysql_devel:
    container_name: mysql_devel_container
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: db_admin_devel
    volumes:
      - mysql_data_devel:/var/lib/mysql
      - ./mysql_conf/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - devel_network
    ports:
      - "3307:3306"

  mysql_prod:
    container_name: mysql_prod_container
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: db_admin
    volumes:
      - mysql_data_prod:/var/lib/mysql
      - ./mysql_conf/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    networks:
      - prod_network
    ports:
      - "3308:3306"

volumes:
  mysql_data_devel:
  mysql_data_prod:

networks:
  devel_network:
    driver: bridge
  prod_network:
    driver: bridge
