name: CICD_Database_Dev_to_Prod

on:
  push:
    branches:
      - master

jobs:
  db_cicd:
    name: Database CI/CD Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: SSH Connect
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "Konek ke server..."
            cd /home/afad/test-cicd
            echo "masuk ke folder test-cicd..."
            echo "${{ secrets.SERVER_PASSWORD }}" | sudo -S docker compose up -d
            echo "docker compose up..."