name: CICD_Database_Dev_to_Prod

on:
  push:
    branches:
      - master

jobs:
  db_cicd:
    name: Database CI/CD Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: SSH Connect
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "Konek ke server..."
            
            cd /home/afad/test-cicd
            echo "masuk ke folder test-cicd..."
            
            echo "docker compse down if running..."
            echo "${{ secrets.SERVER_PASSWORD }}" | sudo -S docker compose down

            echo "docker compose up..."
            echo "${{ secrets.SERVER_PASSWORD }}" | sudo -S docker compose up -d

            # CI (Continuous Integration) untuk database
            echo "Menunggu MySQL untuk siap..."
            echo "${{ secrets.SERVER_PASSWORD }}" | sudo -S sleep 10

            echo "Cek database di development..."
            echo "${{ secrets.SERVER_PASSWORD }}" | sudo -S docker exec mysql_devel_container mysql -u root -padmin123 -e "SHOW DATABASES;"

            # CD (Continuous Deployment) untuk database
            echo "Dump database dari development..."
            echo "${{ secrets.SERVER_PASSWORD }}" | sudo -S docker exec mysql_devel_container mysqldump -u root -padmin123 --databases db_admin_devel > /home/afadfath/test-cicd/db_admin_devel.sql
            
            echo "Copy dump file ke server production..."
            echo "${{ secrets.SERVER_PASSWORD }}" | sudo -S docker cp /home/afadfath/test-cicd/db_admin_devel.sql mysql_prod_container:/tmp/db_admin_devel.sql

            echo "Import dump ke database production..."
            echo "${{ secrets.SERVER_PASSWORD }}" | sudo -S docker exec mysql_prod_container mysql -u root -padmin123 -e "SHOW DATABASES;"
            echo "${{ secrets.SERVER_PASSWORD }}" | sudo -S docker exec mysql_prod_container sh -c "exec mysql -u root -padmin123 db_admin < /tmp/db_admin_devel.sql"